# Generated by Django 5.1.6 on 2025-03-13 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_user'),
        ('vacancyform', '0011_delete_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(verbose_name='О вас')),
                ('resume_file', models.FileField(upload_to='doc', verbose_name='Ваше резюме (.pdf)')),
                ('sendvacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancyform.vacancy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
