# Generated by Django 5.1.6 on 2025-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume_file',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sendvacancy',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about_you',
            field=models.TextField(null=True, verbose_name='О вас'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vacancy_response',
            field=models.TextField(null=True, verbose_name='Отклик на вакансии (Id)'),
        ),
    ]
