# Generated by Django 5.1.6 on 2025-03-06 16:17

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата')),
                ('employment', models.CharField(choices=[('Полная', 'Полная'), ('Частичная', 'Частичная'), ('Полная/Частичная', 'Полная/Частичная')], max_length=30, verbose_name='Занятость')),
                ('work_schedule', models.CharField(max_length=100, verbose_name='График')),
                ('work_hours', models.CharField(max_length=100, verbose_name='Часы работы')),
                ('work_format', models.CharField(max_length=100, verbose_name='Формат работы')),
                ('other', models.TextField(max_length=100000, verbose_name='Другое')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, null=True, verbose_name='Отчество')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('about_us', models.TextField(verbose_name='О вас')),
                ('resume_file', models.FileField(upload_to='doc', verbose_name='Ваше резюме (.pdf)')),
                ('sendvacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancyform.vacancy')),
            ],
        ),
    ]
