# Generated by Django 5.1.6 on 2025-03-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyform', '0005_alter_vacancy_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='slug',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Фото для обложки вакансии'),
        ),
    ]
