# Generated by Django 5.1.6 on 2025-03-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyform', '0008_vacancy_city_vacancy_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата в месяц'),
        ),
    ]
