# Generated by Django 5.1.6 on 2025-03-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyform', '0010_candidate_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
